package katalogdrzew;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.transform.Result;
import javax.xml.transform.Source;
import javax.xml.transform.Transformer;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.dom.DOMSource;
import javax.xml.transform.stream.StreamResult;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.cfg.Configuration;
import org.w3c.dom.Document;
import org.w3c.dom.Element;
import org.w3c.dom.NodeList;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Darek
 */
public class Ramka extends javax.swing.JFrame {

    /**
     * Creates new form Ramka
     */
    public static ArrayList<Drzewo2> kolekcja = new ArrayList();

    public Ramka() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Rodzaj", "Nazwa", "Obwod_pnia"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("lisciaste");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("iglaste");

        jButton1.setText("sortuj");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("WczytajXML");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("ZapiszXML");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("WczytajHB");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Wyczysc");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Zapisz do bazy");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton1)
                    .addComponent(jButton1)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(27, 27, 27)
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton3)
                            .addComponent(jButton4)
                            .addComponent(jButton6))
                        .addContainerGap(30, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButton1)
                        .addGap(66, 66, 66)
                        .addComponent(jRadioButton2)
                        .addGap(61, 61, 61)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5)
                        .addGap(54, 54, 54))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        try {

            DocumentBuilderFactory fabr = DocumentBuilderFactory.newInstance();
            DocumentBuilder parser = fabr.newDocumentBuilder();
            Document dokument = parser.parse("DaneXML.xml");
            Element dane = dokument.getDocumentElement();
            NodeList list = dane.getElementsByTagName("drzewa");

            for (int i = 0; i < list.getLength(); i++) {

                int id = Integer.parseInt(((Element) list.item(i)).getAttribute("id"));
                String Rodzaj = ((Element) list.item(i)).getAttribute("Rodzaj");
                String Nazwa = ((Element) list.item(i)).getAttribute("Nazwa");
                int Obwod_pnia = Integer.parseInt(((Element) list.item(i)).getAttribute("Obwod_pnia"));

                Drzewo2 dane2 = new Drzewo2(id, Rodzaj, Nazwa, Obwod_pnia);

                Object[] d = new Object[4];
                d[0] = dane2.getId();
                d[1] = dane2.getRodzaj();
                d[2] = dane2.getNazwa();
                d[3] = dane2.getObwod_pnia();

                ((DefaultTableModel) jTable1.getModel()).addRow(d);
                kolekcja.add(dane2);

            }
        } catch (Exception ex) {
    }//GEN-LAST:event_jButton2ActionPerformed
    }

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {

            DocumentBuilderFactory fabr = DocumentBuilderFactory.newInstance();
            DocumentBuilder parser = fabr.newDocumentBuilder();
            Document dokument = parser.newDocument();

            Element dane = dokument.createElement("drzewo");
            dokument.appendChild(dane);

            for (Drzewo2 d : kolekcja) {
                Element dane2 = dokument.createElement("drzewa");
                dane2.setAttribute("id", String.valueOf(d.getId()));
                dane2.setAttribute("Rodzaj", d.getRodzaj());
                dane2.setAttribute("Nazwa", d.getNazwa());
                dane2.setAttribute("Obwod_pnia", String.valueOf(d.getObwod_pnia()));
                dane.appendChild(dane2);
            }
            Transformer przekszt = TransformerFactory.newInstance().newTransformer();
            Source zrodlo = new DOMSource(dokument);
            Result wyjscie = new StreamResult("zapis.txt");
            przekszt.transform(zrodlo, wyjscie);
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            SessionFactory fabrykaSesji = new Configuration().configure("javaapplication3/hibernate.cfg.xml").buildSessionFactory();
            Session sesja = fabrykaSesji.openSession();

            Query zapytanie = sesja.createQuery("from Drzewo2");
            ArrayList<Drzewo2> rekordy = (ArrayList<Drzewo2>) zapytanie.list();

            for (Drzewo2 d : rekordy) {
                Object[] dane = new Object[4];
                dane[0] = d.getId();
                dane[1] = d.getRodzaj();
                dane[2] = d.getNazwa();
                dane[3] = d.getObwod_pnia();
                ((DefaultTableModel) jTable1.getModel()).addRow(dane);

                Drzewo2 dane3 = new Drzewo2((int) dane[0], (String) dane[1], (String) dane[2], (int) dane[3]);
                kolekcja.add(dane3);
            }

            sesja.close();

        } catch (Exception ex) {
            System.out.print(ex.getMessage());

        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            // ((DefaultTableModel) jTable1.getModel()).removeRow(0);
            SessionFactory fabrykaSesji = new Configuration().configure("javaapplication3/hibernate.cfg.xml").buildSessionFactory();
            Session sesja = fabrykaSesji.openSession();
            Query zapytanie = sesja.createQuery("from Drzewo2");
            ArrayList<Drzewo2> rekordy = (ArrayList<Drzewo2>) zapytanie.list();

            for (Drzewo2 d : rekordy) {
                Object[] dane = new Object[4];
                dane[0] = d.getId();
                dane[1] = d.getRodzaj();
                dane[2] = d.getNazwa();
                dane[3] = d.getObwod_pnia();

                if (jRadioButton1.isSelected() && d.getRodzaj().equals("lisciaste")) {
                    ((DefaultTableModel) jTable1.getModel()).addRow(dane);
                    Drzewo2 drzewo = new Drzewo2((int) dane[0], (String) dane[1], (String) dane[2], (int) dane[3]);
                    kolekcja.add(drzewo);
                }
//                ((DefaultTableModel) jTable1.getModel()).removeRow(0);
                if (jRadioButton2.isSelected() && d.getRodzaj().equals("iglaste")) {

                    ((DefaultTableModel) jTable1.getModel()).addRow(dane);
                    Drzewo2 drzewo = new Drzewo2((int) dane[0], (String) dane[1], (String) dane[2], (int) dane[3]);
                    kolekcja.add(drzewo);

                }

            }
            sesja.close();
        } catch (Exception ex) {
            System.out.print(ex.getMessage());
    }//GEN-LAST:event_jButton1ActionPerformed
    }
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
    ((DefaultTableModel) jTable1.getModel()).setRowCount(0);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
Connection polaczenie;
try{
    Class.forName("com.mysql.jdbc.Driver").newInstance();
    polaczenie = DriverManager.getConnection("jdbc:mysql://localhost/dane","root","");
    
    Statement instrukcja = polaczenie.createStatement();
    instrukcja.executeUpdate("DELETE FROM tdane");
    
    for (Drzewo2 d : kolekcja) {
        String sql = "INSERT INTO tdane SET ";
        sql += "id='" +d.getId() + "', ";
        sql += "Rodzaj='" +d.getRodzaj() + "', ";
        sql += "Nazwa='" +d.getNazwa() + "', ";
        sql += "Obwod_pnia='" +d.getObwod_pnia() + "'";

        System.out.println(sql);
        instrukcja.executeUpdate(sql);
    }   
    polaczenie.close();
}
catch(Exception ex){ex.getMessage();}
    
    }//GEN-LAST:event_jButton6ActionPerformed
    

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ramka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ramka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ramka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ramka.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ramka().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
